### ISSUE TITLE
Examples for using the software

### ISSUE THREAD

**Issue by kylebeggs** [aliaksei135/seedpod_ground_risk#106]
Hello - can you please add some examples of using the software? A "Getting Started" section would be sufficient in the homepage README. I also don't see a reference to the API. I suppose a lot of this stuff is obvious when using the GUI, but this documentation is needed for the CLI.
Joss Review: openjournals/joss-reviews#4079

**Comment by Zach10a** [comment]
Hi Kyle,

https://github.com/aliaksei135/seedpod_ground_risk/wiki/Use-Case-1

This can be found in the wiki. I have now updated the wiki link as it was outdated.

**Comment by kylebeggs** [comment]
Oh, great! I think it might be a good idea to put a link in the main page README as in my experience, a lot of repos don't make use of the GitHub wiki so it was obvious to go there.
