### ISSUE TITLE
Resize NaN issue

### ISSUE THREAD

**Issue by Zach10a** [aliaksei135/seedpod_ground_risk#24]
Resizing cases the following error message:

```
File "C:\Users\Zach\PycharmProjects\seedpod_ground_risk\seedpod_ground_risk\core\plot_server.py", line 379, in _get_raster_dimensions
    raster_width = int(abs(max_x - min_x) // raster_resolution_m)
ValueError: cannot convert float NaN to integer

```

Fixing #20 would solve this

**Comment by aliaksei135** [comment]
I cannot seem to recreate this anymore on the latest `develop` branch code. Is this is still an issue?

**Comment by Zach10a** [comment]
Managed to recreate this, will be working on it now the new version is out.

**Comment by Zach10a** [comment]
NaN issue only occurs when the user attempts to resize when the image has been zoomed in on for the second time. It comes down to the function in line 34 of utils. The proj.transform appears to be spitting out infinites.
![image](https://user-images.githubusercontent.com/35232913/122293607-18973380-ceef-11eb-8b4c-d914a4077029.png)

**Comment by aliaksei135** [comment]
Does this actually cause any problems, or is it a spurious console output? If the former is false, then this can be closed.
