### ISSUE TITLE
Improve progress update

### ISSUE THREAD

**Issue by aliaksei135** [aliaksei135/seedpod_ground_risk#5]
Current progress updates are few and far between leaving user to wonder if it has crashed or not. This can be improved by adding a more detailed progress callback from the `PlotServer` and display a progress bar to the user.

**Comment by Zach10a** [comment]
Progress bar is ready to go pending updates to generation code. Needs some refinement on the actual position of the progress updates.

**Comment by aliaksei135** [comment]
Thanks! Latest layer gen updates are on `develop` now

**Comment by aliaksei135** [comment]
Fixed by #32
