### ISSUE TITLE
Handle OSM query failures gracefully

### ISSUE THREAD

**Issue by aliaksei135** [aliaksei135/seedpod_ground_risk#61]
Currently any failure in fetching OSM data results in an unhandled exception and complete failure to generate the map without any user notification (aside from the debug console). This should be handled gracefully and generate the risk map without the failed data if possible. Either way the user should be notified of the failure in the UI.

**Comment by Zach10a** [comment]
Partly fixed in the above PR, however this does not allow for the risk map to be produced without the failed data. I will close this and #65 when #66 is merged and if failing data becomes an issue in future will look at implementing that idea.

**Comment by Zach10a** [comment]
The errors being received are <Response 500> (Internal server errors). Still looking to see if something has changed regarding request queries on their side as that's the only thing I can think of that's happened.

**Comment by aliaksei135** [comment]
Okay so I have done a bit more research on this. Here are a few things to try:

- Send as `POST` requests instead of `GET`, like we are doing now
- Set a meaningful `User-Agent` header, something like `seedpod-ground-risk v0.13.0 (Python 3.8/requests v<xxx>;)`
- Set the `Content-Type` header to what it actually is: `application/x-www-form-urlencoded; charset=UTF-8`

**Comment by aliaksei135** [comment]
@Zach10a Good stuff that using POSTs fixed the error. I think it's good practice to implement the other 2 suggestions here while we are on it as well!

**Comment by aliaksei135** [comment]
Closed by #66
