### ISSUE TITLE
Allow switch of Overpass endpoints

### ISSUE THREAD

**Issue by aliaksei135** [aliaksei135/seedpod_ground_risk#65]
Sometimes the Overpass instance will timeout or otherwise fail (see also #61). Currently, only a single Overpass endpoint is statically set in the code (`https://overpass.kumi.systems/api/interpreter`), which doesn't always work. There are other endpoints which can be used in case one of them fails (see [here](https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances)). There are 2 options for implementing this:

1. Allow the user to manually select their preferred endpoint
2. Use the endpoints in a round robin style to distribute the load and likelihood to failure across the pool

Either would be acceptable, 1 would probably be more tedious patching the option through to the UI as the endpoint is used in the async threads that `PlotServer` forks off.

**Comment by Zach10a** [comment]
This is failing because it is throwing an SSLError. This can be solved by parsing varify=False into the requests.get() call but it's not very secure.

**Comment by aliaksei135** [comment]
I would be fine with not verifying SSL certs for connections as there is no secure data being passed (not even an API key). Would be an issue if API keys become introduced in the future by OSM/Overpass.

**Comment by aliaksei135** [comment]
Closed by #66
