### ISSUE TITLE
Make risk map layer parameters equate to the aircraft being simulated

### ISSUE THREAD

**Issue by Zach10a** [aliaksei135/seedpod_ground_risk#70]
At the moment I don't believe the risk map that the algorithm is using actually represents the risk map of the aircraft that the route has been calculated for. I intend to make the default risk map change based on the parameters of the aircraft chosen for the route.

**Comment by Zach10a** [comment]
This also needs to be able to feed into the path analysis popups before being implimented

**Comment by aliaksei135** [comment]
Closed by #77
