### ISSUE TITLE
Reaper unable to be chosen

### ISSUE THREAD

**Issue by Zach10a** [aliaksei135/seedpod_ground_risk#80]
Addition of the dummy variable at the top of the aircraft list has caused the bottom item on the list to not be able to be chosen.

**Comment by Zach10a** [comment]
159 in add_layer_wizard.py

**Comment by aliaksei135** [comment]
A commonly used setting, not sure how we've gone this long without noticing...

**Comment by aliaksei135** [comment]
But realistically this could be happening on all the other dropdowns as well, so that should be checked

**Comment by Zach10a** [comment]
It's not happening on any others, just this one. It's due to the dummy variable being added in, a very easy fix as it just involves adding 1 to the index that is fed back.

**Comment by aliaksei135** [comment]
Closed by #83
