### ISSUE TITLE
Layers update in real-time

### ISSUE THREAD

**Issue by Zach10a** [aliaksei135/seedpod_ground_risk#82]
At the moment the layer list requires the user to generate the map before it rearranges itself and shows the correct list. This would be far better if it updated itself after a layer was added or removed.

**Comment by aliaksei135** [comment]
Agreed, but this would require that the map and controls be disabled for the time that the map is generating. There is too much latency caused by the map generation to do this in real time without the user tearing their hair out waiting after every change to the configuration

**Comment by Zach10a** [comment]
To confirm, I am talking about updating the layer list on the lift in Real-time, not the generated map.

**Comment by aliaksei135** [comment]
Ah okay, that makes more sense. Sounds good, but would suggest that the view changes somehow to distinguish whether a new layer is being made or it is showing what the map is showing. Could be greyed out/different background/italics
